# Generated by Django 2.2 on 2020-12-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('addresss', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=50)),
                ('contact', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_customer',
            },
        ),
    ]
