# Generated by Django 2.2 on 2020-12-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='lname',
            field=models.CharField(default='hello', max_length=30),
            preserve_default=False,
        ),
    ]
