# Generated by Django 2.2 on 2020-12-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='', upload_to='images/')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('totalp', models.FloatField()),
            ],
            options={
                'db_table': 'tbl_product',
            },
        ),
    ]
