# Generated by Django 2.2 on 2020-12-26 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartmodel',
            old_name='emailIdFk',
            new_name='emailfk',
        ),
        migrations.RenameField(
            model_name='cartmodel',
            old_name='ProductQuantity',
            new_name='productfk',
        ),
        migrations.RenameField(
            model_name='cartmodel',
            old_name='productIdFk',
            new_name='productquantity',
        ),
    ]
