# Generated by Django 2.2 on 2020-12-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailfk', models.EmailField(max_length=30)),
                ('date', models.CharField(max_length=30)),
                ('amount', models.IntegerField()),
            ],
            options={
                'db_table': 'tb_order',
            },
        ),
    ]
