# Generated by Django 2.2 on 2020-12-26 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ordermodel',
            table='tbl_order',
        ),
    ]
