# Generated by Django 2.2 on 2020-12-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0003_auto_20201225_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='amount',
            field=models.FloatField(),
        ),
    ]
