# Generated by Django 2.2 on 2020-12-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmodel',
            name='password',
            field=models.CharField(default='admin', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='adminmodel',
            name='username',
            field=models.CharField(default='admin', editable=False, max_length=30),
        ),
    ]
